# Generated by Django 4.2 on 2023-04-19 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventoryapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
